OPTIONS(SKIP=0)
LOAD DATA
CHARACTERSET WE8MSWIN1252
INFILE 'usuario.txt'
INTO TABLE t_us TRUNCATE
FIELDS TRAILING NULLCOLS
(
c1 BOUNDFILLER POSITION(1:10),
carne ":c1",
nombre POSITION(12:61) "TRIM(:nombre)",
clave POSITION(63:112) "TRIM(:clave)",
tipo POSITION(114:163) "TRIM(:tipo)"
)

